// Auspicious by Design — full catalogue data
// 78 items from the Corona Family Collection, each identified by its stock code.
//
// NOTE ON NUMBERING: the book's "plates" are PRINTING PLATES — they number the
// PHOTOGRAPHS, not the furniture. Several items are photographed across more than
// one plate (SC81 front and back; SB200 full view and details; the pairs SB230P,
// SB193P1 and EB108P). The site therefore numbers ITEMS (no. 1-78) and treats the
// book's plate numbers as image references, exposed as `bookImages`.
//
// Source: "Auspicious by Design: A Collection of Antique Tibetan Painted Furniture"
// Mera Publications, 2021 (ISBN 978-9937-0-8899-2)
// Text by Camilla Corona, photography by Kishore & Hari Mahajan

const CATALOGUE = [
  // ══════════════════════════════════════════════
  // I. MONASTIC TRUNKS & BOXES (No. 1–28)
  // ══════════════════════════════════════════════
  { no: 1, code: "SB126", category: "boxes", title: "\"Lhoka Box\"",
    period: "15th–16th Century", origin: "Southern Tibet", dimensions: "34 × 136 · H 67cm", sold: true,
    bookImages: [13],
    images: [{ file: "plate_13.jpg", label: "Full view" }],
    description: "A classic early \"Lhoka box\" with vertical side panels extending beyond the horizontal panel to form short legs. The front displays a splendid flaming jewel in the central cartouche, representing the Three Jewels of Tibetan Buddhism — the Buddha, the teachings, and the community. A bold, colourful pattern delimits the plain field, with circular Wheels of Joy in the four corners." },
  { no: 2, code: "SB289", category: "boxes", title: "\"Lhoka Box\"",
    period: "15th–16th Century", origin: "Southern Tibet", dimensions: "40 × 117 · H 61cm",
    bookImages: [14],
    images: [{ file: "plate_14.jpg", label: "Full view" }],
    description: "A scallop-shaped section carved around the front and sides of this trapezoid box. The central lobed frame contains a lotus flower emerging from stylized scrolling waves, holding the Sanskrit syllable \"OM\" in the Lantsha script, with clouds above. The cinnabar red field contrasts with simple corner scrolls." },
  { no: 3, code: "SB175", category: "boxes", title: "\"Lhoka Box\"",
    period: "15th–16th Century", origin: "Southern Tibet", dimensions: "35 × 113 · H 54cm",
    bookImages: [15],
    images: [{ file: "plate_15.jpg", label: "Full view" }],
    description: "Trapezoid in shape, tapering towards a flat lid with a carved scalloped section. At centre is a cluster of flaming jewels resting on a lotus flower. The All Powerful Ten interlocking symbols of the Kalachakra mantra are written on either side in the Lantsha script." },
  { no: 4, code: "SB200", category: "boxes", title: "Monastic Box",
    period: "15th Century or earlier", origin: "Central Tibet", dimensions: "49 × 116 · H 57cm",
    bookImages: [16, 17],
    images: [{ file: "plate_17.jpg", label: "Full view" }, { file: "plate_16.jpg", label: "Detail of the cartouche" }, { file: "plate_16_b.jpg", label: "Detail of the side panel" }],
    description: "A powerful depiction of Black Zambala, the wrathful god of wealth, standing on a lotus flower with a coloured aureole behind him. He holds a skull cup full of blood and a mongoose vomiting jewels. To either side are two figures bent under the weight of jewel-filled sacks — one a Tibetan, the other a snake-like naga." },
  { no: 5, code: "SB159", category: "boxes", title: "Monastic Box",
    period: "15th–16th Century", origin: "Central Tibet", dimensions: "48 × 139 · H 68cm",
    bookImages: [18],
    images: [{ file: "plate_18.jpg", label: "Full view" }],
    description: "A chakra wheel at centre — one of the Eight Auspicious Symbols, offered by Brahma to the Buddha to \"turn the wheel of the Dharma.\" The rare aubergine background with bold floral design wraps around the sides of the box. The colour, made from cochineal, was historically expensive." },
  { no: 6, code: "SB227", category: "boxes", title: "\"Lhoka Box\"",
    period: "15th–16th Century", origin: "Central Tibet", dimensions: "45 × 145 · H 68cm",
    bookImages: [19],
    images: [{ file: "plate_19.jpg", label: "Full view" }],
    description: "A scalloped section carved around the front and sides forms a distinct top border. The lobed oblong frame at centre contains a floral design resembling Chinese silk and velvet textile patterns from the 16th–17th century Ming period. Continuous trefoil cloud-scrolls (jui'i) decorate the brown border." },
  { no: 7, code: "SB332", category: "boxes", title: "\"Lhoka Box\"",
    period: "15th–16th Century", origin: "Southern Tibet", dimensions: "50 × 135 · H 67cm",
    bookImages: [20],
    images: [{ file: "plate_20.jpg", label: "Full view" }],
    description: "A trapezoid box tapering towards the top. At its centre is a cluster of elongated jewels with rounded tops, resting on a lotus blossom inside a lobed roundel with a yellow then green aureole. The colour scheme, bold simplicity and excellent condition make it a delightful early box." },
  { no: 8, code: "SB222", category: "boxes", title: "Monastic Box",
    period: "18th Century", origin: "Central Tibet", dimensions: "54 × 147 · H 71cm",
    bookImages: [21],
    images: [{ file: "plate_21.jpg", label: "Full view" }],
    description: "A wonderfully understated box decorated with the kyung bur raised gesso technique. Two gold Chinese shou characters — symbols of longevity — sit in the field. Real gold on a cinnabar red background, with touches of blue and green reserved for the lotus and central flaming jewel." },
  { no: 9, code: "SB424", category: "boxes", title: "\"Brocade\" Box",
    period: "16th–17th Century", origin: "Central Tibet", dimensions: "36 × 81 · H 44cm",
    bookImages: [22],
    images: [{ file: "plate_22.jpg", label: "Full view" }],
    description: "A sinuous dragon curls in an almost full circle in the central cartouche, clasping a single large jewel. The dragon has two long horns and a long snout reminiscent of those on early Ming porcelains. Leather binding on the edges indicates the box was used to transport rolls of silk brocade." },
  { no: 10, code: "SB421", category: "boxes", title: "Monastic Box",
    period: "16th–17th Century", origin: "Central Tibet", dimensions: "36 × 81 · H 43cm",
    bookImages: [23],
    images: [{ file: "plate_23.jpg", label: "Full view" }],
    description: "Found by Luca in a Lhasa dealer's \"Aladdin's cave\" alongside Mongolian warrior artefacts from a soldier's grave near Drigung. The lattice design (kati rimo) is inspired by Ming lampas weaves. The central medallion holds a jewel on a red and gold lotus flower." },
  { no: 11, code: "SB228", category: "boxes", title: "Monastic Box",
    period: "16th–17th Century", origin: "Central Tibet", dimensions: "34 × 102 · H 48cm",
    bookImages: [24],
    images: [{ file: "plate_24.jpg", label: "Full view" }, { file: "plate_24_detail.jpg", label: "Detail of the cartouche" }],
    description: "Depicts two of the Four Great Kings, Guardians of the cardinal directions. Virupaksha (red, guardian of the West) holds a small stupa; Virudhaka (green, guardian of the South) holds a sword. Both wear jewelled crowns and flowing scarves over their armour." },
  { no: 12, code: "SB230P", category: "boxes", title: "Pair of Monastic Boxes",
    period: "16th–17th Century", origin: "Central Tibet", dimensions: "33 × 84 · H 44cm",
    bookImages: [25, 26],
    images: [{ file: "plate_25.jpg", label: "First of the pair" }, { file: "plate_26.jpg", label: "Second of the pair" }, { file: "plate_26_detail.jpg", label: "Detail of the cartouche" }],
    description: "The Six Symbols of Long Life: Shou Lao, the Chinese god of longevity, sits in the centre as an old man counting his prayers. Behind him: the Tree and the Immutable Rock. Around him: the Water, the Crane, and the Deer. The composition reads as a single cycle of nourishment and life. The second box of the pair centres on Vaishravana, leader of the Four Great Kings and guardian of the North. As wealth-bestowing god, he holds a mongoose that vomits jewels into a golden dish. He sits on a lion and holds a heavenly banner of billowing silks." },
  { no: 13, code: "SB151", category: "boxes", title: "Monastic Box",
    period: "17th–18th Century", origin: "Central Tibet", dimensions: "48 × 129 · H 59cm", sold: true,
    bookImages: [27],
    images: [{ file: "plate_27.jpg", label: "Full view" }, { file: "plate_27_detail.jpg", label: "Detail of the cartouche" }],
    description: "A unique black-and-white colour scheme on a classic design. Within the central lobed medallion, two contorted dragons safeguard a vase of flaming jewels and auspicious symbols. One dragon's body is scaled, the other dotted — perhaps differentiating male and female. Lotus flowers grow from their hair." },
  { no: 14, code: "SB133", category: "boxes", title: "Monastic Box",
    period: "18th Century", origin: "Central Tibet", dimensions: "48 × 125 · H 59cm",
    bookImages: [28],
    images: [{ file: "plate_28.jpg", label: "Full view" }],
    description: "The design is based on the Lantsha script, used by Tibetans for writing mantras. At the centre appears the third letter of the Tibetan alphabet, \"ga\" — a practical way of labelling the box, executed in gilded kyung bur raised gesso." },
  { no: 15, code: "SB193P1", category: "boxes", title: "Pair of Monastic Boxes",
    period: "18th Century", origin: "Central Tibet", dimensions: "40 × 124 · H 59cm",
    bookImages: [29, 30],
    images: [{ file: "plate_29.jpg", label: "First of the pair" }, { file: "plate_30.jpg", label: "Second of the pair" }, { file: "plate_30_detail.jpg", label: "Detail of the cartouche" }],
    description: "Two dragons face one another with long snouts almost touching, above a golden bowl of jewels and auspicious symbols. The triple lobed border contains the kati rimo trellis design, clearly inspired by Ming brocades. Rosettes connect to roundels with bold lattice work. The second box of the pair features two golden phoenixes — legendary birds living 500 years before rising from their ashes. Each has a parrot's beak, a peacock's tail, and long crane-like legs. In Chinese mythology, phoenixes appear only where there is peace, prosperity, and happiness." },
  { no: 16, code: "SB385", category: "boxes", title: "Monastic Box",
    period: "18th Century", origin: "Central Tibet", dimensions: "43 × 127 · H 64cm",
    bookImages: [31],
    images: [{ file: "plate_31.jpg", label: "Full view" }],
    description: "From the classic period of Central Tibetan boxes. Two dragons swirl amongst clouds in the enlarged central cartouche, their bodies made of golden raised dots that diminish in size towards the extremities. They face each other holding a cluster of flaming jewels between them." },
  { no: 17, code: "SB326", category: "boxes", title: "Monastic Box",
    period: "18th Century", origin: "Central Tibet", dimensions: "46 × 122 · H 63cm",
    bookImages: [32],
    images: [{ file: "plate_32.jpg", label: "Full view" }],
    description: "A beautiful bird dominates the lobed central cartouche — an imaginary mix of a crane's head, neck, wings and legs, with a phoenix's colour and feathery tail. Six small golden auspicious symbols sit on the plain cinnabar field. The whole composition is extremely balanced." },
  { no: 18, code: "SB218", category: "boxes", title: "Monastic Box",
    period: "18th Century", origin: "Central Tibet", dimensions: "42 × 113 · H 62cm",
    bookImages: [33],
    images: [{ file: "plate_33.jpg", label: "Full view" }],
    description: "A golden dragon with raised gesso scales (rather than the more typical dots) appears to juggle jewels near his claws and mouth. A simple kati rimo lattice design fills the field, with golden scrolls adorning the corners." },
  { no: 19, code: "SB565", category: "boxes", title: "Monastic Box",
    period: "18th Century", origin: "Central Tibet", dimensions: "45 × 138 · H 62cm",
    bookImages: [34],
    images: [{ file: "plate_34.jpg", label: "Full view" }],
    description: "Luca saw this box arrive on a truck in Lhasa entirely black with soot, except for one cleaned patch revealing the marvellous palette beneath. A side-facing dragon holds two golden bowls of jewels in his claws, swirling amongst red and blue lotus flowers." },
  { no: 20, code: "SB195", category: "boxes", title: "Monastic Box",
    period: "18th Century", origin: "Central Tibet", dimensions: "44 × 148 · H 89cm",
    bookImages: [35],
    images: [{ file: "plate_35.jpg", label: "Full view" }],
    description: "A rare pure silver background — most \"silver\" boxes were silver-leafed and yellow-varnished to imitate gold. A front-facing dragon curls within the double-bordered lobed frame, hovering above stylized mountains, his golden scales made from diminishing kyung bur bumps." },
  { no: 21, code: "SB140", category: "boxes", title: "Monastic Box",
    period: "18th Century", origin: "Central Tibet", dimensions: "48 × 126 · H 59cm",
    bookImages: [36],
    images: [{ file: "plate_36.jpg", label: "Full view" }],
    description: "The painter abandoned the typical central cartouche, releasing the dragons without constraint on the front of the box. A huge lotus rises from scrolling plants, supporting a magnificent array of flaming jewels (norbu rinpoche). The dragons float towards each other amongst exotic plants." },
  { no: 22, code: "SB226", category: "boxes", title: "Monastic Box",
    period: "18th Century", origin: "Central Tibet", dimensions: "48 × 132 · H 67cm",
    bookImages: [37],
    images: [{ file: "plate_37.jpg", label: "Full view" }],
    description: "A riot of colour with no part left unpainted. In the lobed central medallion, a side-facing dragon holds a golden tray of round jewels and elephant tusks, surrounded by a variety of lotus and other flowers. His four fangs are bared, with eyes rolling backwards." },
  { no: 23, code: "SB444", category: "boxes", title: "Monastic Box",
    period: "18th Century", origin: "Central Tibet", dimensions: "45 × 139 · H 63cm",
    bookImages: [38],
    images: [{ file: "plate_38.jpg", label: "Full view" }],
    description: "Real gold on red, indicating destination for use in monasteries — most likely an offering to the monastery itself. Two dragons swirl down from the top to face each other, supporting a vase brimming with round and oblong jewels. Bilva fruit — an important Indian offering — adorns the field." },
  { no: 24, code: "SB557", category: "boxes", title: "Monastic Box",
    period: "18th Century", origin: "Central Tibet", dimensions: "45 × 119 · H 59cm",
    bookImages: [39],
    images: [{ file: "plate_39.jpg", label: "Full view" }],
    description: "In the central cartouche, a sinuous dragon clasps jewels in his claws and swirls amongst clouds and jewels on strings. The field is plain red with golden corner scrolls; the wide border contains lotus flowers surrounded by foliage." },
  { no: 25, code: "SB142", category: "boxes", title: "Monastic Box",
    period: "18th Century", origin: "Central Tibet", dimensions: "40 × 131 · H 62cm",
    bookImages: [40],
    images: [{ file: "plate_40.jpg", label: "Full view" }],
    description: "Likely from Tsurpu Monastery, traditional seat of the Karmapa. Decorated entirely in gold on gold — kyung bur on a golden background, achieved using a sheep-intestine syringe filled with gesso, glue, resin, sugar and linseed oil. The Seven Gems surround a vase of flaming jewels." },
  { no: 26, code: "SB235", category: "boxes", title: "Monastic Box",
    period: "18th Century", origin: "Central Tibet", dimensions: "49 × 144 · H 73cm (105cm with stand)",
    bookImages: [41],
    images: [{ file: "plate_41.jpg", label: "Full view" }],
    description: "A perfect example of a classic 18th-century dragon box, complete with stand. Two dragons swirl down amongst lotus flowers, holding up a golden dish containing the Eight Auspicious Symbols. Between their arms is a lotus with a cluster of flaming jewels." },
  { no: 27, code: "SB221", category: "boxes", title: "Monastic Box",
    period: "18th Century", origin: "Central Tibet", dimensions: "37 × 105 · H 52cm",
    bookImages: [42],
    images: [{ file: "plate_42.jpg", label: "Full view" }],
    description: "A fine side-facing dragon emerges from water in the lower lobed section, holding a green bowl of jewels in one hand and clasping a striped jewel in the four claws of the other. The unusual blue background — symbolizing sky — sets off the elaborate kati rimo lattice." },
  { no: 28, code: "EB108P", category: "boxes", title: "Pair of Monastic Boxes",
    period: "18th Century", origin: "Central Tibet", dimensions: "54 × 143 · H 72cm (110cm with stand)",
    bookImages: [43, 44],
    images: [{ file: "plate_43.jpg", label: "First of the pair" }, { file: "plate_44.jpg", label: "Second of the pair" }],
    description: "A remarkable pair, complete with stands. In the central cartouche, a front-facing dragon holds a golden tray of jewels, flanked by two side-facing dragons clasping round jewels. The Eight Auspicious Symbols appear in the field, each in a circle of green or blue. When Luca made his offer, the rival Lhasa–Kathmandu dealer conceded with the remark: “I have never seen such beautiful boxes — the front is just like a precious piece of brocade.”" },
  // ══════════════════════════════════════════════
  // II. LEATHER TRUNKS (No. 29–30)
  // ══════════════════════════════════════════════
  { no: 29, code: "SL191P", category: "leather", title: "Pair of Leather Trunks",
    period: "18th–19th Century", origin: "Central Tibet", dimensions: "30 × 75 · H 40cm",
    bookImages: [45],
    images: [{ file: "plate_45.jpg", label: "Full view" }],
    description: "A stunning pair of large leather boxes, used as storage trunks (rather than for travel). Decorative leather patches on the top, sides and front in highly gilded and embossed leather — possibly Russian or European in origin. Dale Gluckman noted \"gilded Russian leather was among the gifts from the Panchen Lama to Warren Hastings in 1774.\"" },
  { no: 30, code: "SL193", category: "leather", title: "Leather Trunk",
    period: "18th–19th Century", origin: "Central Tibet", dimensions: "33 × 83 · H 46cm",
    bookImages: [46],
    images: [{ file: "plate_46.jpg", label: "Full view" }],
    description: "Exceptional taste of Tibetan craftsmen on display. Embossed leather patches decorated with silver and gold. Four bone-shaped, brocade-covered patches ornament the front. The latch and irons are inlaid with silver to produce attractive damascened plates — characteristic of work from Derge in Kham." },
  // ══════════════════════════════════════════════
  // III. CABINETS & ALTARS (No. 31–58)
  // ══════════════════════════════════════════════
  { no: 31, code: "SC836", category: "cabinets", title: "Pegam Cabinet",
    period: "18th Century", origin: "Central Tibet", dimensions: "42 × 80 · H 99cm",
    bookImages: [47],
    images: [{ file: "plate_47.jpg", label: "Full view" }],
    description: "A pegam-style cabinet with scalloped panels around the top, back and sides. Beautifully pictorial: the Six Symbols of Longevity, a high dignitary receiving offerings, the Chinese monk Hvashang surrounded by children, a forest scene with deer and wolves, and a caravan crossing a wooden bridge into a trading city on stilts." },
  { no: 32, code: "SC364", category: "cabinets", title: "Pegam Cabinet",
    period: "19th Century", origin: "Central Tibet", dimensions: "34 × 67 · H 77cm",
    bookImages: [48],
    images: [{ file: "plate_48.jpg", label: "Full view" }],
    description: "A characteristic scalloped back and side panels. The front has one door and two fixed panels decorated with bold lotus blossom and green leaves on red. The sides depict a gakyil — Tibetan Wheel of Joy — in four swirling colours representing earth, water, fire and air." },
  { no: 33, code: "SC225", category: "cabinets", title: "Kham Cabinet",
    period: "19th Century", origin: "Eastern Tibet", dimensions: "35 × 144 · H 94cm",
    bookImages: [49],
    images: [{ file: "plate_49.jpg", label: "Full view" }],
    description: "Typical of Kham — thick frame, bold design, mainly decorative. On the side panels, a female deer and male deer (perhaps a unicorn). Centre: a Wheel of Joy surrounded by a dramatic continuous swastika pattern. Lower panels show peacocks bent to eat flowers, and a lotus holding a single jewel." },
  { no: 34, code: "SC388", category: "cabinets", title: "Kham Cabinet",
    period: "19th Century", origin: "Eastern Tibet", dimensions: "32 × 143 · H 92cm", sold: true,
    bookImages: [50],
    images: [{ file: "plate_50.jpg", label: "Full view" }],
    description: "A striking cabinet with five drawers and a sliding door. On the door is a large cluster of jewels from the Seven Jewels of Royal Power; the other six appear on the panels: the Precious General, Wheel, Queen, King, Jewel, Elephant, and Horse — each carrying jewels." },
  { no: 35, code: "SC203", category: "cabinets", title: "Kham Altar",
    period: "19th Century", origin: "Eastern Tibet", dimensions: "40 × 102 · H 140cm",
    bookImages: [51],
    images: [{ file: "plate_51.jpg", label: "Full view" }],
    description: "A cupboard whose exterior decoration suggests it stored wealth vases and torma, while inside, carved niches indicate use as an altar. On each lower door panel: a snow lion with flowing green mane dancing on flaming jewels, holding a jewel in one hand and coral in the other." },
  { no: 36, code: "SC837", category: "cabinets", title: "Kham Altar Cabinet",
    period: "19th Century", origin: "Eastern Tibet", dimensions: "48 × 237 · H 86cm", sold: true,
    bookImages: [52],
    images: [{ file: "plate_52.jpg", label: "Full view" }, { file: "plate_52_detail.jpg", label: "Detail of the panels" }],
    description: "A stunning cabinet from a set, probably the base for an altar. Seven drawers above, seven fixed panels below, two fixed and six opening panels in the middle. The lower panels show a continuous snowflake-shaped flower pattern in alternating green and blue on red." },
  { no: 37, code: "SC329", category: "cabinets", title: "Cabinet",
    period: "19th Century", origin: "Central Tibet", dimensions: "53 × 123 · H 116cm",
    bookImages: [53],
    images: [{ file: "plate_53.jpg", label: "Full view" }],
    description: "A well-proportioned cabinet with four central doors. Each features a roundel with rag dul (Dutch gold) background and an oblong lobed cartouche containing a polychrome phoenix in full flight amongst clouds. Side panels show a flower in a flower-shaped frame; lower panels carry a continuous swastika." },
  { no: 38, code: "SC259", category: "cabinets", title: "Cabinet",
    period: "18th–19th Century", origin: "Central Tibet", dimensions: "38 × 127 · H 116cm",
    bookImages: [54],
    images: [{ file: "plate_54.jpg", label: "Full view" }],
    description: "Likely used in a monastery or lama's apartment given the colour scheme and fine execution. Concentric gold frames contain scrolling designs with jewels executed in very fine gilded kyung bur on a red background. The top right panel shows genuine wear from the latch." },
  { no: 39, code: "SC379", category: "cabinets", title: "Carved Cabinet",
    period: "19th Century", origin: "Central Tibet", dimensions: "43 × 86 · H 108cm",
    bookImages: [55],
    images: [{ file: "plate_55.jpg", label: "Full view" }],
    description: "A rare Central Tibetan cabinet with carved doors. The background is a carved red continuous swastika pattern. The top right depicts the Four Friends — elephant supporting monkey, supporting hare, supporting bird — a Buddhist parable of mutual support and friendship." },
  { no: 40, code: "SC205", category: "cabinets", title: "Cabinet",
    period: "19th–Early 20th Century", origin: "Central Tibet", dimensions: "47 × 121 · H 101cm",
    bookImages: [56],
    images: [{ file: "plate_56.jpg", label: "Full view" }],
    description: "Three drawers above, two opening doors flanked by two fixed panels, and three lower fixed panels. Each panel features a central scrolling medallion with floral design on red. Surrounded by rag dul — imitation gold — with the design executed in kyung bur." },
  { no: 41, code: "SC305", category: "cabinets", title: "Cabinet",
    period: "19th–Early 20th Century", origin: "Central Tibet", dimensions: "47 × 123 · H 107cm",
    bookImages: [57],
    images: [{ file: "plate_57.jpg", label: "Full view" }],
    description: "Full of life and colour. The four central door roundels each contain a pictorial scene: a Tibetan house party with dancers; Chinese figures viewing a scroll; the Four Friends fable in a beautiful meadow; and Tibetan aristocrats who have adopted the Chinese custom of dining at a chair-and-table." },
  { no: 42, code: "SC221", category: "cabinets", title: "Cabinet",
    period: "19th–Early 20th Century", origin: "Central Tibet", dimensions: "39 × 78 · H 96cm",
    bookImages: [58],
    images: [{ file: "plate_58.jpg", label: "Full view" }],
    description: "The dealer told Luca that the lady selling it had asked for it to go to \"a good person.\" On a rag dul background, an endless knot is the central symbol. Tendrils weave through, leading to stylized flowers. A floral and scroll design decorates the corners on red." },
  { no: 43, code: "SC385", category: "cabinets", title: "Cabinet",
    period: "19th Century", origin: "Central Tibet", dimensions: "50 × 125 · H 107cm",
    bookImages: [59],
    images: [{ file: "plate_59.jpg", label: "Full view" }],
    description: "A \"red and black\" cabinet — caused when gold leaf wore away leaving the base to oxidize. In a double central cartouche is a scrolling tree dragon imitating early Yuan brocades: the design is more scrolling plant than dragon, with just a dragon head at centre." },
  { no: 44, code: "SC208", category: "cabinets", title: "Cabinet",
    period: "19th Century", origin: "Central Tibet", dimensions: "51 × 116 · H 89cm",
    bookImages: [60],
    images: [{ file: "plate_60.jpg", label: "Full view" }],
    description: "A general-use cabinet, likely one of a pair. Four of six panels open. The round lobed central medallion holds a floral composition: a large flower emerging from a pool of water, surrounded by blossoms and green leaves on gold. Geometric scroll design in blue on red marks the corners." },
  { no: 45, code: "SC720P", category: "cabinets", title: "Pair of Cabinets",
    period: "Early 20th Century", origin: "Central Tibet", dimensions: "45 × 85 · H 102cm",
    bookImages: [61],
    images: [{ file: "plate_61.jpg", label: "Full view" }],
    description: "A charming pair of cabinets with strong Chinese symbolism. One depicts the corpulent Hvashang surrounded by children, the Mongolian man holding a chained tiger (representing the three great bodhisattvas), Shou Lao on a deer, and the Four Friends. The other shows Chinese children playing, peaceful cranes, and a Tibetan snow lion meeting a Chinese lion." },
  { no: 46, code: "SC380", category: "cabinets", title: "Torgam-Altar",
    period: "18th Century", origin: "Central Tibet", dimensions: "29 × 43 · H 86cm",
    bookImages: [62],
    images: [{ file: "plate_62.jpg", label: "Full view" }],
    description: "Painted in classic 18th-century style on the outside, this divided cupboard had a niche above for an image and a torgam below. Inside, the doors display exuberant wrathful offerings: looping strings of intestines, the Five Qualities of Enjoyment, vultures carrying eyes, and a naga with a jewel." },
  { no: 47, code: "SC501", category: "cabinets", title: "Cabinet",
    period: "19th Century", origin: "Central Tibet", dimensions: "46 × 108 · H 130cm",
    bookImages: [63],
    images: [{ file: "plate_63.jpg", label: "Full view" }],
    description: "A pictorial cabinet straight out of a Tibetan story book. The top left shows a Tibetan tent lunch party inside a walled city. Below, a Potala-like white-and-red monastery with elephants and Lamas arriving on horseback. Seven further panels show the Chinese monk Hvashang, the Six Symbols of Longevity, horsemen, and the Four Friends." },
  { no: 48, code: "SC81", category: "cabinets", title: "Pegam Table",
    period: "19th Century", origin: "Central Tibet", dimensions: "28 × 66 · H 55cm",
    bookImages: [64, 65],
    images: [{ file: "plate_64.jpg", label: "Front" }, { file: "plate_65.jpg", label: "Back" }],
    description: "A pegam painted on all four sides — the back would face anyone entering the room. A small sliding opening in the front holds small items; decorated with a green lotus flower supporting a flaming jewel. On the scalloped section, three red and green lotus blossoms with foliage." },
  { no: 49, code: "SC427", category: "cabinets", title: "Altar",
    period: "19th Century", origin: "Central Tibet", dimensions: "42 × 55 · H 107cm",
    bookImages: [66],
    images: [{ file: "plate_66.jpg", label: "Full view" }],
    description: "A delightful little altar with six niches on the top, each carved with golden leaves around the arch. Below: a shelf for the seven small bowls of water — the typical offerings filled fresh every morning. The crown is carved with a chotseg pattern of miniature cubes, finishing in a triangular point." },
  { no: 50, code: "SC202", category: "cabinets", title: "Yangam Cabinet",
    period: "19th–Early 20th Century", origin: "Kham", dimensions: "49 × 94 · H 115cm",
    bookImages: [67],
    images: [{ file: "plate_67.jpg", label: "Full view" }],
    description: "The left door shows the Six Symbols of Long Life with water as a stream depositing jewels, peacocks flying around the tree, and the Eight Auspicious Symbols above. The right door shows the Seven Jewels of Royal Power, the Eight Bringers of Good Fortune, armour, and the Seven Gems. The painter omitted no auspicious detail." },
  { no: 51, code: "SC794", category: "cabinets", title: "Yangam Cabinet",
    period: "18th–19th Century", origin: "Central Tibet", dimensions: "40 × 54 · H 53cm",
    bookImages: [68],
    images: [{ file: "plate_68.jpg", label: "Full view" }],
    description: "Most probably executed by a thangka painter. The left door shows the Six Symbols of Longevity with an added beautiful lady pouring liquid (perhaps the elixir of immortality) for a crane. The right door shows Hvashang — sent by the Tang Emperor to invite the Arhats — with his fat belly symbolizing wealth and his smile, equanimity." },
  { no: 52, code: "SC835", category: "cabinets", title: "Pegam Cabinet",
    period: "18th–19th Century", origin: "Central Tibet", dimensions: "57 × 35 (+6.5) · H 41cm (+24cm back)",
    bookImages: [69],
    images: [{ file: "plate_69.jpg", label: "Full view" }],
    description: "A pegam whose centre panel opens. Each panel is decorated with a large Chinese auspicious character in gold, worn to leave the dark base contrasting with the red background. Corner scrolls in kyung bur on green; raised golden dots and a wide blue border." },
  { no: 53, code: "ST640", category: "cabinets", title: "Pegam Cabinet",
    period: "18th–19th Century", origin: "Central Tibet", dimensions: "37 (+9) × 46 · H 42cm",
    bookImages: [70],
    images: [{ file: "plate_70.jpg", label: "Full view" }],
    description: "A charming table with a solid frame reinforced with metal strips bent around the corners. The doors and sides are decorated with a polychrome scroll pattern on greenish background. The back panel — carved scalloped — features Sanskrit letters in the Lantsha script." },
  { no: 54, code: "SC661", category: "cabinets", title: "Torgam Cabinet",
    period: "19th–Early 20th Century", origin: "Tibet", dimensions: "34 × 59 · H 107cm",
    bookImages: [71],
    images: [{ file: "plate_71.jpg", label: "Full view" }],
    description: "A startling representation of the wrathful face with bulging eyes, a third eye, flames above the eyebrows, gaping mouth with teeth and fangs. Inside the mouth, a curling tongue holds a person whose legs and head stick out either side. Severed heads and skulls line the central frame." },
  { no: 55, code: "SC246", category: "cabinets", title: "Torgam Cabinet",
    period: "19th Century", origin: "Central Tibet", dimensions: "40 × 65 · H 86cm",
    bookImages: [72],
    images: [{ file: "plate_72.jpg", label: "Full view" }],
    description: "For storing torma — ritual offering cakes made from tsampa, butter and dried cheese. Each door shows the wrathful face: bulging eyes, golden flame eyebrows, a third eye, mouth wide open with fangs, a crown of skulls topped with golden jewels, and a real snake necklace." },
  { no: 56, code: "SC797", category: "cabinets", title: "Torgam Cabinet",
    period: "19th Century", origin: "Central Tibet", dimensions: "37 × 117 · H 69cm", sold: true,
    bookImages: [73],
    images: [{ file: "plate_73.jpg", label: "Full view" }],
    description: "Used as an altar with four niches for Buddhist deity images, and a torgam in the central section. The two central doors depict Mahakala's wrathful face on red: three bulging eyes, flaming eyebrows and beard in gilded kyung bur, a pig-like nose, and a huge open mouth showing four fangs." },
  { no: 57, code: "SC821", category: "cabinets", title: "Torgam Cabinet",
    period: "19th Century", origin: "Central Tibet", dimensions: "31 × 55 · H 62cm",
    bookImages: [74],
    images: [{ file: "plate_74.jpg", label: "Full view" }],
    description: "A fierce brown wrathful Mahakala head with three bulging eyes, golden flaming eyebrows and moustache, four fangs, and ears with long lobes hung with big jewels. Around his neck: dismembered limbs — arms on one panel, legs and feet on the other. Two snow lions support the torgam from below." },
  { no: 58, code: "SC386", category: "cabinets", title: "Yangam Cabinet",
    period: "19th Century", origin: "Central Tibet", dimensions: "44 × 77 · H 64cm", sold: true,
    bookImages: [75],
    images: [{ file: "plate_75.jpg", label: "Full view" }],
    description: "Almost minimalist for Tibetan taste. One peacock on one door (wings open, tail spread, neck curled up); a dragon on the other (emerging from waves, holding jewels amongst flames, facing the peacock). Both look at the same spot — an extraordinarily restrained composition." },
  // ══════════════════════════════════════════════
  // IV. TABLES (No. 59–78)
  // ══════════════════════════════════════════════
  { no: 59, code: "ST89", category: "tables", title: "Cabinet",
    period: "18th–19th Century", origin: "Central Tibet", dimensions: "39 × 82 · H 62cm",
    bookImages: [76],
    images: [{ file: "plate_76.jpg", label: "Full view" }],
    description: "The curling fern flower pattern shows undeniable Kashmiri influence — trade in arts and crafts flowed through Ladakh in the West or via Nepal in the South. A pictorial sliding panel shows a seated lama, snow mountains, and a European-dressed figure directing trade by what may be a mosque." },
  { no: 60, code: "ST262", category: "tables", title: "Table",
    period: "19th–Early 20th Century", origin: "Central Tibet", dimensions: "38 × 77 · H 49cm",
    bookImages: [77],
    images: [{ file: "plate_77.jpg", label: "Full view" }],
    description: "A drawer running the length of the table opens from one side. The front and sides are divided by a carved rounded frame marked at intervals to imitate bamboo. The top panel shows a floral scene with water, rocks, and beautiful blue, pink and green peony blossoms on red." },
  { no: 61, code: "ST88", category: "tables", title: "Table",
    period: "19th Century", origin: "Central Tibet", dimensions: "36 × 76 · H 58cm",
    bookImages: [78],
    images: [{ file: "plate_78.jpg", label: "Full view" }],
    description: "The predominantly red and gold colouring makes this ideal for a monastery or lama's apartment. The two side panels are divided into triangles with a diamond shape in the middle, outlined in gold. A door forms the middle panel; round jewels interconnected by a golden thread frame the design." },
  { no: 62, code: "ST371", category: "tables", title: "Table",
    period: "19th Century", origin: "Central Tibet", dimensions: "33 × 98 · H 33cm",
    bookImages: [79],
    images: [{ file: "plate_79.jpg", label: "Full view" }],
    description: "A long, low offering table with an open back, plain sides and a highly decorative front. Three magnificent lotus blossoms hold up three of the Five Qualities of Enjoyment: Silk (touch), Conch shell as Incense Vessel (smell), and Fruit (taste). The Mirror and Lute are missing — perhaps once one of a pair." },
  { no: 63, code: "ST380", category: "tables", title: "Table",
    period: "19th–Early 20th Century", origin: "Central Tibet", dimensions: "37 × 87 · H 47cm",
    bookImages: [80],
    images: [{ file: "plate_80.jpg", label: "Full view" }],
    description: "A general-use table (chog tse) with a drawer running its length. Tastefully decorated with foliage and three large lotus flowers on the main front panel. Often Tibetan decoration is so abundant focus is hard — here enough background is left plain to give justice to detailed shading." },
  { no: 64, code: "ST156", category: "tables", title: "Kham Table",
    period: "19th–Early 20th Century", origin: "Eastern Tibet", dimensions: "36 × 98 · H 46cm",
    bookImages: [81],
    images: [{ file: "plate_81.jpg", label: "Full view" }],
    description: "Two front drawers; a lower panel that slides into grooves on either side. The drawers depict a man playing music, a dancing lady, ladies bringing offerings to a god. The lower panel shows the Seven Secondary Jewels of the Chakravartin, and the emblems of three bodhisattvas: Manjushri, Avalokiteshvara, and Vajrapani." },
  { no: 65, code: "ST40P", category: "tables", title: "Pair of Folding Tables",
    period: "19th Century", origin: "Central Tibet", dimensions: "34 × 71 · H 35cm",
    bookImages: [82],
    images: [{ file: "plate_82.jpg", label: "Full view" }],
    description: "Folding tables where front and side panels fold into the top for storage — ideal for the Tibetan lifestyle, brought out for special occasions, pujas, and picnics. Decorated with an unusual turquoise background and golden medallions of sacks tied with auspicious symbols, encircling Chinese characters." },
  { no: 66, code: "ST215", category: "tables", title: "Table",
    period: "18th–19th Century", origin: "Central Tibet", dimensions: "27 × 80 · H 33cm",
    bookImages: [83],
    images: [{ file: "plate_83.jpg", label: "Full view" }],
    description: "Two small drawers at the top open from the back; one long drawer running the length opens from one side and locks from the other. A Kashmiri-inspired composition: delicately painted flower clusters on a green background outside, brown inside. Above the top edge: cloud-shaped flower patterns on gold." },
  { no: 67, code: "ST133", category: "tables", title: "Table",
    period: "18th–19th Century", origin: "Central Tibet", dimensions: "35 × 83 · H 42cm",
    bookImages: [84],
    images: [{ file: "plate_84.jpg", label: "Full view" }],
    description: "A chog tse table for general use. The recessed front panel is beautifully decorated with three golden phoenixes forming individual roundels with their curved wings. They are separated by golden lotus flowers and an auspicious Chinese symbol on a black background." },
  { no: 68, code: "ST624", category: "tables", title: "Table",
    period: "19th–20th Century", origin: "Central Tibet", dimensions: "24 × 80 · H 41cm",
    bookImages: [85],
    images: [{ file: "plate_85.jpg", label: "Full view" }],
    description: "A small offering table with a solid frame, overhanging top, and open back and sides — painted only on the front. The lower apron features a kyung bur zipac (\"Face of Majesty\") with sun and moon above his head, two horns and two hands. Below: the Seven Gems and five offering goddesses." },
  { no: 69, code: "ST134", category: "tables", title: "Table",
    period: "19th–Early 20th Century", origin: "Central Tibet", dimensions: "39 × 80 · H 39cm",
    bookImages: [86],
    images: [{ file: "plate_86.jpg", label: "Full view" }],
    description: "A zipac with scaly skin made in gilded kyung bur \"goose bumps,\" a green jewel in his mouth, two horns and curly hair. On either side: a snow lion with green mane below snow mountains; a garuda wrapped half on front, half on side, biting a snake; and the Four Friends amongst blossoms." },
  { no: 70, code: "ST627", category: "tables", title: "Table",
    period: "18th Century", origin: "Central Tibet", dimensions: "21 × 46 · H 16cm",
    bookImages: [87],
    images: [{ file: "plate_87.jpg", label: "Full view" }],
    description: "A stand for offerings on top of an altar. Front, top and back are one piece of wood hollowed out; sides held by flattened iron strips. The front is carved into a central scallop with floral pattern in kyung bur — gilded gold worn away leaving a black base contrasting beautifully with the red." },
  { no: 71, code: "ST93", category: "tables", title: "Table",
    period: "18th–19th Century", origin: "Central Tibet", dimensions: "41 × 90 · H 59cm",
    bookImages: [88],
    images: [{ file: "plate_88.jpg", label: "Full view" }],
    description: "A medium-sized table, higher than the general-use chog tse, used in front of a raised seat. Solid frame structure with straight legs and two box stretchers. Open-work carving executed with a fret saw in a bow-shaped design, with scrolls akin to hanging bunches of grapes." },
  { no: 72, code: "ST447", category: "tables", title: "Table",
    period: "18th Century", origin: "Central Tibet", dimensions: "20 × 48 · H 30cm",
    bookImages: [89],
    images: [{ file: "plate_89.jpg", label: "Full view" }],
    description: "A delightful carved table that opens on both sides — a panel slides up through the thick tray top. Sturdy red frame, inserted carved panel in front with a scrolling wave-like design on turquoise background, red petals, traces of gold. Carved rectangles below the top." },
  { no: 73, code: "ST481", category: "tables", title: "Table",
    period: "17th–18th Century", origin: "Central Tibet", dimensions: "28 × 97 · H 47cm",
    bookImages: [90],
    images: [{ file: "plate_90.jpg", label: "Full view" }, { file: "plate_90_detail.jpg", label: "Detail of the carved apron" }],
    description: "A rudimentary structure with side planks and open back. Small holes in adjacent panels allowed a leather thread to bind them until the glue dried — a simple ingenious method. The elaborate decoration suggests an offering table: deep chiselled relief scrolls with leaves, a central tray on a lotus blossom, and carved lotus flowers around the top edge." },
  { no: 74, code: "ST626", category: "tables", title: "Table",
    period: "15th–16th Century or earlier", origin: "Central Tibet", dimensions: "32 × 64 · H 29cm",
    bookImages: [91],
    images: [{ file: "plate_91.jpg", label: "Full view" }],
    description: "Two carved makara — mythical sea creatures from ancient India with elephant trunks, wild-boar ears, monkey eyes, fish bodies, lion's paws and peacock tails. Between them, a rotating gakhyil (Wheel of Joy) symbolizes the three jewels: Buddha, Dharma, Sangha. On the sides, \"OM\" and \"AM\" in Lantsha script." },
  { no: 75, code: "ST164", category: "tables", title: "Table",
    period: "16th–17th Century", origin: "Southern Tibet", dimensions: "36 × 75 · H 40cm",
    bookImages: [92],
    images: [{ file: "plate_92.jpg", label: "Full view" }],
    description: "Newari-influenced — the craftsmen of the Kathmandu Valley were famed for detailed carving. Cabriole legs bent inwards, thicker at the top, tapering to swirls. The front panel features the mythical zipac (or kirtimukha) holding branches that fan into scrolling patterns. Below: the Eight Auspicious Symbols. No paint; a sooty patina from centuries near a smoky stove." },
  { no: 76, code: "ST313", category: "tables", title: "Table",
    period: "15th–17th Century", origin: "Central Tibet", dimensions: "82 × 42 · H 45cm",
    bookImages: [93],
    images: [{ file: "plate_93.jpg", label: "Full view" }],
    description: "A row of carved scrolls under the overhanging top, then a red panel with two small rectangles containing scrolling decoration. The main feature: the mythical zipac with sun and moon on his head, two horns, bushy eyebrows, an open mouth without a lower jaw — surrounded by scrolls. Cabriole legs end in elaborate scrolls." },
  { no: 77, code: "ST625", category: "tables", title: "Table",
    period: "15th–17th Century", origin: "Central Tibet", dimensions: "38 × 97 · H 43cm",
    bookImages: [94],
    images: [{ file: "plate_94.jpg", label: "Full view" }, { file: "plate_94_detail.jpg", label: "Detail of the carved apron" }],
    description: "In Tibetan: kyisu — \"dog-legged\" — where the cabriole leg's upper convex curve tapers to a concave, ending with carved foliage scrolls. At centre is a large triple jewel emerging from a lotus, with half-palmettes fanning out behind and deep scroll carving on either side." },
  { no: 78, code: "ST623", category: "tables", title: "Table",
    period: "17th Century", origin: "Central Tibet", dimensions: "33 × 79 · H 62cm", sold: true,
    bookImages: [95],
    images: [{ file: "plate_95.jpg", label: "Full view" }],
    description: "A table for placement in front of a raised seat or small throne. Straight back legs and carved front \"dog-legs\" curling into scrolls at the bottom. The rectangular front panel is interrupted by a carved altar cloth — draped down the front, hanging with perfect folds." },
];

const CATEGORIES = [
  { id: "boxes",    label: "Tibetan Monastic Trunks & Boxes",     subtitle: "Sacred forms of storage, painted with dragons, jewels & cloud scrolls.", period: "15th – 19th Century" },
  { id: "leather",  label: "Tibetan Leather Trunks",              subtitle: "For the road — travelled forms, tooled and burnished.", period: "18th – 19th Century" },
  { id: "cabinets", label: "Tibetan Cabinets & Altars",           subtitle: "Structures for the sacred and the daily — carved, layered, painted.", period: "18th – 20th Century" },
  { id: "tables",   label: "Tibetan Tables",                      subtitle: "Decorated to the elevation of the seat — by rank, by rite.", period: "15th – 20th Century" },
];

// Period lookup for filtering
function getCentury(period) {
  const match = period.match(/(\d{1,2})/);
  return match ? parseInt(match[1]) : null;
}

if (typeof module !== "undefined") module.exports = { CATALOGUE, CATEGORIES, getCentury };
